// frontend/src/components/FeeInvoiceDetail.jsx

import { useState, useEffect } from 'react';
import {
  FEE_INVOICES_URL,
  apiFetch,
} from '../api';

// Note: this modal only shows details. Payment recording is added in Step 9.

function FeeInvoiceDetail({ invoiceId, onClose, onRecordPayment }) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const load = async () => {
    setLoading(true);
    setError('');
    try {
      const res = await apiFetch(`${FEE_INVOICES_URL}/${invoiceId}`);
      const json = await res.json();
      if (!res.ok) throw new Error(json.message || 'Failed to load invoice');
      setData(json.data);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (invoiceId) load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [invoiceId]);

  const inv = data?.invoice;
  const payments = data?.payments || [];

  const handlePrint = () => {
    window.print();
  };

  return (
    <div style={styles.overlay} onClick={onClose}>
      <div
        className="fee-invoice-printable"
        style={styles.modal}
        onClick={(e) => e.stopPropagation()}
      >
        <div style={styles.header}>
          <div>
            <h2 style={styles.title}>Invoice Details</h2>
            <p style={styles.subtitle}>
              {inv?.invoiceNo ? `${inv.invoiceNo} · ${inv.periodLabel || inv.period}` : 'Loading...'}
            </p>
          </div>
          <button style={styles.closeBtn} onClick={onClose}>✕</button>
        </div>

        <div style={styles.body}>
          {loading ? (
            <p style={styles.info}>Loading...</p>
          ) : error ? (
            <p style={styles.error}>{error}</p>
          ) : !inv ? (
            <p style={styles.info}>Invoice not found.</p>
          ) : (
            <>
              {/* Student info */}
              <div style={styles.studentCard}>
                {inv.student?.picture && (
                  <img
                    src={inv.student.picture}
                    alt=""
                    style={styles.studentPhoto}
                    onError={(e) => { e.target.style.display = 'none'; }}
                  />
                )}
                <div style={styles.studentInfo}>
                  <div style={styles.studentName}>{inv.student?.name}</div>
                  <div style={styles.studentMeta}>
                    Reg No: <strong>{inv.student?.regNo || '—'}</strong>
                    {inv.enrollment?.rollNo && (
                      <> · Roll: <strong>{inv.enrollment.rollNo}</strong></>
                    )}
                  </div>
                  <div style={styles.studentMeta}>
                    {inv.class?.name} · {inv.academicYear?.name}
                  </div>
                </div>
                <div style={styles.amountBox}>
                  <div style={styles.amountLabel}>Balance</div>
                  <div
                    style={{
                      ...styles.amountValue,
                      color: inv.totalAmount - inv.paidAmount > 0 ? '#dc3545' : '#10b981',
                    }}
                  >
                    Rs {Math.max(0, inv.totalAmount - inv.paidAmount).toLocaleString()}
                  </div>
                  <div style={styles.amountSub}>
                    of Rs {inv.totalAmount.toLocaleString()}
                  </div>
                </div>
              </div>

              {/* Invoice meta */}
              <div style={styles.metaGrid}>
                <div style={styles.metaCell}>
                  <div style={styles.metaLabel}>Issue Date</div>
                  <div style={styles.metaValue}>{inv.issueDate || '—'}</div>
                </div>
                <div style={styles.metaCell}>
                  <div style={styles.metaLabel}>Due Date</div>
                  <div style={styles.metaValue}>{inv.dueDate || '—'}</div>
                </div>
                <div style={styles.metaCell}>
                  <div style={styles.metaLabel}>Status</div>
                  <div style={styles.metaValue}>
                    <span style={{ ...styles.statusBadge, ...statusStyle(inv.status) }}>
                      {inv.status}
                    </span>
                  </div>
                </div>
                <div style={styles.metaCell}>
                  <div style={styles.metaLabel}>Generated By</div>
                  <div style={styles.metaValue}>{inv.generatedBy?.username || '—'}</div>
                </div>
              </div>

              {/* Line items */}
              <h3 style={styles.sectionTitle}>Line Items</h3>
              <table style={styles.table}>
                <thead>
                  <tr style={styles.thead}>
                    <th style={styles.th}>#</th>
                    <th style={styles.th}>Head</th>
                    <th style={styles.th}>Frequency</th>
                    <th style={styles.th}>Description</th>
                    <th style={{ ...styles.th, textAlign: 'right' }}>Amount</th>
                  </tr>
                </thead>
                <tbody>
                  {(inv.lineItems || []).map((li, i) => (
                    <tr key={i} style={styles.tr}>
                      <td style={styles.td}>{i + 1}</td>
                      <td style={styles.td}><strong>{li.head}</strong></td>
                      <td style={styles.td}>{li.frequency || '—'}</td>
                      <td style={styles.td}>{li.description || '—'}</td>
                      <td style={{ ...styles.td, textAlign: 'right' }}>
                        Rs {Number(li.amount).toLocaleString()}
                      </td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr style={styles.tfootRow}>
                    <td colSpan="4" style={{ ...styles.td, textAlign: 'right' }}>Subtotal</td>
                    <td style={{ ...styles.td, textAlign: 'right' }}>
                      Rs {Number(inv.subtotal).toLocaleString()}
                    </td>
                  </tr>
                  {inv.discount > 0 && (
                    <tr style={styles.tfootRow}>
                      <td colSpan="4" style={{ ...styles.td, textAlign: 'right' }}>
                        Discount
                      </td>
                      <td style={{ ...styles.td, textAlign: 'right', color: '#10b981' }}>
                        − Rs {Number(inv.discount).toLocaleString()}
                      </td>
                    </tr>
                  )}
                  {inv.lateFee > 0 && (
                    <tr style={styles.tfootRow}>
                      <td colSpan="4" style={{ ...styles.td, textAlign: 'right' }}>
                        Late Fee
                      </td>
                      <td style={{ ...styles.td, textAlign: 'right', color: '#dc3545' }}>
                        + Rs {Number(inv.lateFee).toLocaleString()}
                      </td>
                    </tr>
                  )}
                  <tr style={styles.tfootTotal}>
                    <td colSpan="4" style={{ ...styles.td, textAlign: 'right' }}>
                      <strong>Total</strong>
                    </td>
                    <td style={{ ...styles.td, textAlign: 'right' }}>
                      <strong>Rs {Number(inv.totalAmount).toLocaleString()}</strong>
                    </td>
                  </tr>
                </tfoot>
              </table>

              {/* Payments */}
              <h3 style={styles.sectionTitle}>
                Payments ({payments.length})
              </h3>
              {payments.length === 0 ? (
                <p style={styles.noPayments}>
                  No payments recorded yet.
                </p>
              ) : (
                <table style={styles.table}>
                  <thead>
                    <tr style={styles.thead}>
                      <th style={styles.th}>#</th>
                      <th style={styles.th}>Receipt</th>
                      <th style={styles.th}>Date</th>
                      <th style={styles.th}>Method</th>
                      <th style={styles.th}>Reference</th>
                      <th style={styles.th}>By</th>
                      <th style={{ ...styles.th, textAlign: 'right' }}>Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    {payments.map((p, i) => (
                      <tr key={p._id} style={styles.tr}>
                        <td style={styles.td}>{i + 1}</td>
                        <td style={styles.td}>
                          <span style={styles.receiptNo}>{p.receiptNo}</span>
                        </td>
                        <td style={styles.td}>{p.paymentDate}</td>
                        <td style={styles.td}>
                          <span style={styles.methodPill}>{p.method}</span>
                        </td>
                        <td style={styles.td}>{p.referenceNo || '—'}</td>
                        <td style={styles.td}>
                          {p.receivedBy?.username || '—'}
                        </td>
                        <td style={{ ...styles.td, textAlign: 'right' }}>
                          <strong>Rs {Number(p.amount).toLocaleString()}</strong>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot>
                    <tr style={styles.tfootTotal}>
                      <td colSpan="6" style={{ ...styles.td, textAlign: 'right' }}>
                        <strong>Total Paid</strong>
                      </td>
                      <td style={{ ...styles.td, textAlign: 'right' }}>
                        <strong>Rs {Number(inv.paidAmount).toLocaleString()}</strong>
                      </td>
                    </tr>
                  </tfoot>
                </table>
              )}
            </>
          )}
        </div>

        <div style={styles.footer}>
          <button style={styles.printBtn} onClick={handlePrint} disabled={!inv}>
            🖨️ Print Invoice
          </button>
          <button
            style={{
              ...styles.paymentBtn,
              opacity: inv?.status === 'paid' || inv?.status === 'waived' ? 0.5 : 1,
              cursor:
                inv?.status === 'paid' || inv?.status === 'waived'
                  ? 'not-allowed'
                  : 'pointer',
            }}
            onClick={() => onRecordPayment(inv)}
            disabled={!inv || inv.status === 'paid' || inv.status === 'waived'}
          >
            💰 Record Payment
          </button>
          <button style={styles.closePrimary} onClick={onClose}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

// Helper for status colors
function statusStyle(status) {
  const map = {
    unpaid: { backgroundColor: '#fee2e2', color: '#991b1b' },
    partial: { backgroundColor: '#fef3c7', color: '#92400e' },
    paid: { backgroundColor: '#d4edda', color: '#155724' },
    overdue: { backgroundColor: '#fecaca', color: '#7f1d1d' },
    waived: { backgroundColor: '#e0e7ff', color: '#3730a3' },
  };
  return map[status] || map.unpaid;
}

const styles = {
  overlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.65)',
    zIndex: 2000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
  },
  modal: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    width: '100%',
    maxWidth: '1000px',
    maxHeight: '92vh',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: 'Arial, sans-serif',
    boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: '20px 24px',
    borderBottom: '1px solid #e3e8f0',
  },
  title: { margin: 0, fontSize: '20px', color: '#1e2a4a' },
  subtitle: { margin: '4px 0 0', fontSize: '13px', color: '#6b7280' },
  closeBtn: {
    background: 'none',
    border: 'none',
    fontSize: '20px',
    cursor: 'pointer',
    color: '#6b7280',
    padding: '4px 10px',
    borderRadius: '6px',
  },
  body: { padding: '20px 24px', overflowY: 'auto', flex: 1 },
  info: { textAlign: 'center', color: '#6b7280', padding: '30px' },
  error: { textAlign: 'center', color: '#dc3545', padding: '30px' },

  studentCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '16px',
    backgroundColor: '#eef3fb',
    borderRadius: '10px',
    marginBottom: '18px',
    flexWrap: 'wrap',
  },
  studentPhoto: {
    width: '60px',
    height: '60px',
    borderRadius: '50%',
    objectFit: 'cover',
    border: '3px solid #fff',
  },
  studentInfo: { flex: 1, minWidth: '180px' },
  studentName: { fontSize: '17px', fontWeight: 'bold', color: '#1e2a4a' },
  studentMeta: { fontSize: '12px', color: '#4b5563', marginTop: '3px' },
  amountBox: {
    textAlign: 'right',
    padding: '10px 16px',
    backgroundColor: '#fff',
    borderRadius: '8px',
    minWidth: '150px',
  },
  amountLabel: {
    fontSize: '10px',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  amountValue: {
    fontSize: '22px',
    fontWeight: 'bold',
    lineHeight: 1.2,
    marginTop: '2px',
  },
  amountSub: { fontSize: '11px', color: '#6b7280', marginTop: '2px' },

  metaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '10px',
    marginBottom: '20px',
  },
  metaCell: {
    padding: '8px 12px',
    backgroundColor: '#f8fafc',
    borderRadius: '6px',
    border: '1px solid #eef1f6',
  },
  metaLabel: {
    fontSize: '10px',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: '0.4px',
  },
  metaValue: {
    fontSize: '13px',
    fontWeight: 'bold',
    color: '#1e2a4a',
    marginTop: '3px',
  },
  statusBadge: {
    padding: '3px 10px',
    borderRadius: '12px',
    fontSize: '11px',
    fontWeight: 'bold',
    textTransform: 'capitalize',
    display: 'inline-block',
  },

  sectionTitle: {
    fontSize: '14px',
    color: '#1e2a4a',
    marginTop: '20px',
    marginBottom: '10px',
    paddingBottom: '6px',
    borderBottom: '1px solid #eef1f6',
  },

  table: {
    width: '100%',
    borderCollapse: 'collapse',
    marginTop: '6px',
  },
  thead: { backgroundColor: '#1e2a4a', color: '#fff' },
  th: {
    padding: '8px 10px',
    textAlign: 'left',
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '0.4px',
  },
  tr: { borderBottom: '1px solid #eef1f6' },
  td: { padding: '8px 10px', fontSize: '13px' },
  tfootRow: {
    backgroundColor: '#f8fafc',
  },
  tfootTotal: {
    backgroundColor: '#eef3fb',
    borderTop: '2px solid #4a72c4',
  },

  receiptNo: {
    backgroundColor: '#eef3fb',
    color: '#4a72c4',
    padding: '2px 8px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  methodPill: {
    backgroundColor: '#f1f3f5',
    color: '#1e2a4a',
    padding: '2px 8px',
    borderRadius: '12px',
    fontSize: '11px',
    fontWeight: 'bold',
    textTransform: 'capitalize',
  },
  noPayments: {
    color: '#9ca3af',
    fontSize: '13px',
    fontStyle: 'italic',
    padding: '12px',
    textAlign: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: '6px',
  },

  footer: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '10px',
    padding: '16px 24px',
    borderTop: '1px solid #e3e8f0',
    backgroundColor: '#fafbfd',
    flexWrap: 'wrap',
  },
  printBtn: {
    padding: '10px 20px',
    backgroundColor: '#6f42c1',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: 'bold',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  paymentBtn: {
    padding: '10px 20px',
    backgroundColor: '#10b981',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: 'bold',
    fontFamily: 'inherit',
  },
  closePrimary: {
    padding: '10px 20px',
    backgroundColor: '#4a72c4',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: 'bold',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
};

export default FeeInvoiceDetail;